files:
  - source: /public/locales/en-US/grafana.json
    translation: /public/locales/%locale%/%original_file_name%
    type: i18next_json
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
