version: 2.1
machine: true

executors:
  docker-executor:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo

commands:
  docker_build_stage:
    description: "docker build grafana-tl `docker_target` image"
    parameters:
      docker_target:
        type: string
    steps:
      - run:
          name: Docker build target << parameters.docker_target >>
          working_directory: ~/repo
          command: |
            docker build --target << parameters.docker_target >> \
                          --tag << parameters.docker_target >>:local \
                          .

  docker_push_stage:
    description: "docker pushes grafana-tl `docker_target` image"
    parameters:
      docker_target:
        type: string
    steps:
      - run:
          name: Docker push target << parameters.docker_target >>
          working_directory: ~/repo/airflow-extra
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              export GRAFANA_VERSION=$(cat /tmp/workspace/generated_version)
              echo "This commit is tagged, also pushing this to releases"
              docker login -u $TERAREPO_USER -p $TERAREPO_PASSWORD docker.terarepo.net
              docker tag <<parameters.docker_target>>:local docker.terarepo.net/<<parameters.docker_target>>:${GRAFANA_VERSION}
              docker push docker.terarepo.net/<<parameters.docker_target>>:${GRAFANA_VERSION} | cat
              docker logout docker.terarepo.net
            fi

jobs:
  generate_version:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Generate git describe Python version >> workspace/generated_version
          command: |
            mkdir -p workspace
            python setup.py --version
            python setup.py --version >> workspace/generated_version
      - run:
          name: Print workspace/generated_version
          command: |
            export VERSION=$(cat workspace/generated_version)
            echo "'${VERSION}'"
      - persist_to_workspace:
          root: workspace
          paths: generated_version

  docker_grafana-tl:
    description: "Build Grafana-TL Dockers"
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - docker_build_stage:
          docker_target: grafana-tl
      - docker_push_stage:
          docker_target: grafana-tl

workflows:
  version: 2
  ci_magic:
    jobs:
      - generate_version:
          filters:
            tags:
              only: /.*/
      - docker_grafana-tl:
          requires:
            - generate_version
          filters:
            tags:
              only: /.*/
