---
apiVersion: v1
kind: Endpoints
metadata:
  name: example-apiserver
subsets:
  - addresses:
      - ip: 172.17.0.1 # this is the gateway IP in the "bridge" docker network
    ports:
      - appProtocol: https
        port: 7443
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: example-apiserver
spec:
  ports:
    - protocol: TCP
      appProtocol: https
      port: 7443
      targetPort: 7443
