name: New Bug Report
description: File a bug report
title: "Product-Area-Here: short description of bug here"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please try to give your issue a good title. Try using the product-area where you are having an issue and a brief description of the problem. Like this: 
        - `Dashboards: Template Variables break when I do X` or 
        - `Alerting: message templating plus Slack channel breaks when I do X`
  - type: markdown
    attributes:
      value: |
        **HINT:** Have you tried [searching](https://github.com/grafana/grafana/issues) for similar issues? Duplicate issues are common.

        **Are you reporting a security vulnerability?** [Submit it here instead](https://github.com/grafana/grafana/security/policy).
  - type: markdown
    attributes:
      value: |
       #

  - type: textarea
    attributes:
      label: What happened?
      description: "**Hot Tip:** Record your screen and add it here as a gif."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Did this work before?
      placeholder: "If this worked before, what version worked correctly?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: How do we reproduce it?
      description: |
        Whenever possible, please provide **detailed** steps for reproducing your bug.
        **This is very helpful info**
      placeholder: "Step 1:..."
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment (with versions)?
      description: |
        #
        Please provide Grafana, OS, and Browser versions.
        [How do I find my Grafana version info?](https://community.grafana.com/t/how-to-find-your-grafana-version-info-3-different-ways/86857)
      placeholder: "ex: v9.5.0, or v9.5.0-cloud.5.a016665c (b2a5d45589)"
      value: |
        Grafana:
        OS:
        Browser:
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Grafana Platform?
      description: How are you running/deploying Grafana?
      options:
        - I use Grafana Cloud
        - Docker
        - Kubernetes
        - A package manager (APT, YUM, BREW, etc.)
        - A downloaded binary
        - Other
        - I don't know
    validations:
      required: false

  - type: input
    attributes:
      label: Datasource(s)?
      description: "Is this issue specific to a datasource plugin/plugins? Please list all that apply:"
      placeholder: "ex. Elasticsearch 5.0.0 or Infinity 1.4.1 ..."

  - type: textarea
    attributes:
      label: Is the bug inside a Dashboard Panel?
      description: |
        If the bug appears inside a [dashboard panel](https://grafana.com/docs/grafana/latest/panels-visualizations/#panels-and-visualizations), please use the ["Get-Help" feature](https://grafana.com/docs/grafana/latest/troubleshooting/send-panel-to-grafana-support/). Select **copy to clipboard** and paste the data below.
        No need for backticks--this text will get formatted as a code-block.
        What's a [dashboard panel](https://grafana.com/docs/grafana/latest/panels-visualizations/#panels-and-visualizations)?
      placeholder: Copy "get-help" data here
