# my global config
global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.yml"
  - "recording.yml"
# - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'fake-data-gen'
    static_configs:
      - targets: ['fake-prometheus-data:9091']

  - job_name: 'grafana'
    static_configs:
<<<<<<< HEAD
      - targets: ['grafana:3000']
||||||| parent of d42a5b2561... FrontendMetrics: Adds new backend api that frontend can use to push frontend measurements and counters to prometheus (#32593)
      - targets: ['127.0.0.1:3000']
=======
      - targets: ['host.docker.internal:3000']
>>>>>>> d42a5b2561... FrontendMetrics: Adds new backend api that frontend can use to push frontend measurements and counters to prometheus (#32593)

  - job_name: 'prometheus-random-data'
    static_configs:
      - targets: ['prometheus-random-data:8080']
