name: Automatical cherry picking (test action)

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Parse Milestone
        uses: ./.github/actions/grafana-parse-milestone
        id: parseMilestone
      - name: Echo
        run: echo "The parsed milestone was ${{ steps.parseMilestone.outputs.major }}"
