name: Bump version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch, major.minor.patch-preview or major.minor.patch-preview<number> format. example: 7.4.3, 7.4.3-preview or 7.4.3-preview1'
        required: true
      push:
        default: true
        required: false
      dry_run:
        default: true
        required: false
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2.0.2
        if: ${{ github.event.inputs.version != '' }}
        id: regex-match
        with:
          text: ${{ github.event.inputs.version }}
          # https://semver.org/
          regex: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
      - name: Validate input version
        if: ${{ steps.regex-match.outputs.match == '' && github.event.inputs.version != '' }}
        run: |
          echo "The input version format is not correct, please respect:\
          major.minor.patch, major.minor.patch-preview or major.minor.patch-preview<number> format. \
          example: 7.4.3, 7.4.3-preview or 7.4.3-preview1"
          exit 1
      - uses: actions/checkout@v4
      # Go is required for 'make gen-cue' and for the 'go run' in the dagger action
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Bump versions
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run ./pkg/build/workflows/bump-version -version=${{ inputs.version }}
      - name: make gen-cue
        run: make gen-cue
      - if: ${{ inputs.push }}
        name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_DELIVERY_BOT_APP_PEM }}
      - if: ${{ inputs.push }}
        name: Push & Create PR
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "bump-version/${{ github.run_id }}/${{ inputs.push }}"
          git add .
          git commit -m "bump version ${{ inputs.version }}"
          gh pr create -l "backport ${{ inputs.backport }}" --dry-run=${{ inputs.dry_run }} -H "release/${{ inputs.version }}" -B "${{ inputs.target }}" --title "Release: ${{ inputs.version }}" --body "These code changes must be merged after a release is complete"
