name: doc-validator
on:
  pull_request:
    paths: ["docs/sources/**"]
  workflow_dispatch:
jobs:
  docs-target:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.target.outputs.target }}
    steps:
      - name: Checkout Actions library
        uses: actions/checkout@v3
        with:
          repository: grafana/grafana-github-actions
          path: ./actions

      - name: Install Actions from library
        run: npm install --production --prefix ./actions

      - name: Determine technical documentation version
        uses: ./actions/docs-target
        id: target
        with:
          ref_name: ${{ github.base_ref }}
