# This action is responsible for running `go mod tidy` to sync go dependencies.
name: go tidy

on:
  push:
    branches:
    - master
    - v[0-9]+.[0-9]+.[0-9]+

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
  USERNAME: grafanabot
  EMAIL: bot@grafana.com

jobs:
  tidy-master:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Git
        run: |
          git config user.name ${USERNAME}
          git config user.email ${EMAIL}
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/grafana/grafana.git
      -
        name: Run go mod tidy
        run: |
          rm -f go.sum
          go mod tidy
      -
        name: Commit and push go.sum
        run: |
          git add .
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Update go module dependencies'
            git push
          fi
