name: Fix Crowdin I18n files

on:
  pull_request:
    paths:
      - 'public/locales/*/grafana.json'
    branches:
      - main

jobs:
  fix-files:
    if: github.head_ref == 'crowdin-service-branch'
    name: Fix files
    runs-on: ubuntu-latest
    permissions:
      contents: write # write permission needed to commit changes back in
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Extract I18n files
        run: yarn i18n:extract

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix up I18n files
          file_pattern: public/locales/*/grafana.json
