name: Prepare release
on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'The version to be released please respect: major.minor.patch or major.minor.patch-beta<number> format. example: 7.4.3 or 7.4.3-beta1'
        required: true
jobs:
  call-bump-version:
    uses: ./.github/workflows/bump-version.yml
    with:
      version_call: ${{ github.event.inputs.version_input }}
    secrets:
      token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
      metricsWriteAPIKey: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
  call-update-changelog:
    uses: ./.github/workflows/update-changelog.yml
    with:
      version_call: ${{ github.event.inputs.version_input }}
    secrets:
      token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
      metricsWriteAPIKey: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
    needs: call-bump-version
