name: Prepare release
on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'The version to be released please respect: major.minor.patch or major.minor.patch-beta.number format. example: 7.4.3 or 7.4.3-beta.1'
        required: true

jobs:
  # call-remove-milestone:
  #   uses: grafana/grafana/.github/workflows/remove-milestone.yml@main
  #   with:
  #     version_call: ${{ github.event.inputs.version_input }}
  # call-close-milestone:
  #   uses: grafana/grafana/.github/workflows/close-milestone.yml@main
  #   with:
  #     version_call: ${{ github.event.inputs.version_input }}
  #   needs: call-remove-milestone
  call-bump-version:
    runs-on: ubuntu-latest
      steps:
        name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: mob/bump-version-update-user-essentials
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run bump version
        uses: ./actions/bump-version
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
          metricsWriteAPIKey: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
  #   needs: call-close-milestone
  # call-update-changelog:
  #   uses: grafana/grafana/.github/workflows/update-changelog.yml@main
  #   with:
  #     version_call: ${{ github.event.inputs.version_input }}
  #   needs: call-bump-version
