name: "publish-kinds-next"

# Temporary - for tests
on:
  push:
    branches:
      - "agnestoulet/kind-registry"
# on:
#   push:
#     branches:
#       - "main"
#   workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version: '1.20.4'

      - name: "Verify kinds"
        run: go run .github/workflows/scripts/kinds/verify-kinds.go
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Generate token"
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.GRAFANA_BOT_APP_ID }}
          private_key: ${{ secrets.GRAFANA_BOT_APP_PEM }}

      - name: "Clone website-sync Action"
        # WEBSITE_SYNC_TOKEN is a fine-grained GitHub Personal Access Token that expires.
        # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
        # GitHub administrator to update the organization secret.
        # The IT helpdesk can update the organization secret.
        run: "git clone --single-branch --no-tags --depth 1 -b master https://grafanabot:${{ steps.generate_token.outputs.token }}@github.com/grafana/website-sync ./.github/actions/website-sync"

      - name: "Publish to kind registry (next)"
        uses: "./.github/actions/website-sync"
        id: "publish-next"
        with:
          repository: "grafana/kind-registry"
          branch: "main"
          host: "github.com"
          # PUBLISH_TO_KIND_REGISTRY_TOKEN is a fine-grained GitHub Personal Access Token that expires.
          # It must be regenerated in the grafanabot GitHub account and requires a Grafana organization
          # GitHub administrator to update the organization secret.
          # The IT helpdesk can update the organization secret.
          github_pat: "grafanabot:${{ steps.generate_token.outputs.token }}"
          source_folder: ".github/workflows/scripts/kinds/next"
          target_folder: "grafana/next"
