# Scan files using sonarcloud. 
  
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      sonarCloudEndpointName: 'SC'
      sonarCloudOrganization: 'vesaninja'
      sonarCloudProjectKey: 'vesaninja_grafana'
      sonarCloudProjectName: 'grafana'
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: 1837a8effa57d6e4ae2287bd6410ec7aefabcf51
