
# Only runs if anything under the packages/ directory changes.
# (Otherwise detect-breaking-changes-build-skip.yml takes over)

name: Levitate / Test PR Comment

on:
  pull_request:
    paths:
      - 'packages/**'
    branches:
      - 'main'

jobs:
  buildPR:
    name: Test comment post
    runs-on: ubuntu-latest
    steps:
    - name: "Generate token"
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ secrets.GRAFANA_PR_AUTOMATION_APP_ID }}
        private_key: ${{ secrets.GRAFANA_PR_AUTOMATION_APP_PEM }}

    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: test-levitate-pr-comment
        message: |
          THIS IS A COMMENT FOR TESTING PURPOSES ONLY
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
